# Generated by Django 4.1.2 on 2022-10-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Rut')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('image', models.URLField(max_length=254, verbose_name='Link Imagen')),
            ],
        ),
    ]
