# Generated by Django 4.1.2 on 2022-10-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['lastname', 'name', 'id_persona'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
    ]
